services:
  api:
    container_name: jusan-compose-final
    image: jusan-fastapi-final:dockerized 
    restart: on-failure 
  
  nginx:
    container_name: jusan-nginx-final
    image: nginx:mainline
    ports:
      - 8787:80
    depends_on:
      - api
    restart: on-failure  
    volumes:
      - ./jusan-docker-mount.conf:/etc/nginx/conf.d/jusan-docker-mount.conf
      - ./jusan-docker-mount/:/var/www/example
      - ./jusan-fastapi-final.conf:/etc/nginx/conf.d/jusan-fastapi-final.conf
    
