{
 "title": "API Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP average duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_milliseconds_sum{job=\"fastapi_app\"}[5m]) / rate(http_requests_milliseconds_count{job=\"fastapi_app\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Calculator Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "errors_calculator_total",
     "legendFormat": "{instance=\"api:8080\", job=\"fastapi_app\"}"
    }
   ]
  },
  {
   "title": "HTTP requests per route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"fastapi_app\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Last Values",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "floor(last_sum1n)", "legendFormat": "Sum1n" },
    { "expr": "floor(last_fibo)", "legendFormat": "Fibo" },
    { "expr": "floor(list_size)", "legendFormat": "List Size" },
    { "expr": "floor(last_calculator)", "legendFormat": "Calculator" }
   ]
  }
 ]
}