scrape_configs:

  - job_name: 'fastapi_app'  

    metrics_path: '/metrics' 

    scrape_interval: 10s  

    static_configs:
      - targets: ['api:8080'] 

  - job_name: 'node_exporter'

    static_configs:
      - targets: ['node_exporter:9100']

 